### ISSUE TITLE
我执行的时候 报一个 除0错误 是什么情况？

### ISSUE THREAD

**Issue by apeman1949** [Sharpiless/Yolov5-Deepsort#2]
fa@ubuntu:~/Downloads/Yolov5-Deepsort-main$ python3 demo.py
/home/fa/Downloads/Yolov5-Deepsort-main/deep_sort/utils/parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
/home/fa/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
fps: 0
Traceback (most recent call last):
  File "demo.py", line 50, in <module>
    main()
  File "demo.py", line 13, in main
    t = int(1000/fps)
ZeroDivisionError: division by zero

**Comment by Pluto-wei** [comment]
因为没有他E盘的视频文件，没有读取到视频的帧数

**Comment by springfrie** [comment]
????

**Comment by springfrie** [comment]
能具体一下吗？

**Comment by guojun999** [comment]
cap = cv2.VideoCapture('')这一句读取你自己的视频路径，我猜可能是没有读到输入导致一些对象不能实例化？
